=== DagonMetric/angular-build/schemas/favicon-config-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "additionalProperties": true,
    "definitions": {
        "IconDesign": {
            "additionalProperties": true,
            "properties": {
                "androidChrome": {
                    "properties": {
                        "assets": {
                            "properties": {
                                "legacyIcon": {
                                    "type": "boolean"
                                },
                                "lowResolutionIcons": {
                                    "type": "boolean"
                                }
                            },
                            "type": "object"
                        },
                        "manifest": {
                            "properties": {
                                "declared": {
                                    "type": "boolean"
                                },
                                "display": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "onConflict": {
                                    "type": "string"
                                },
                                "orientation": {
                                    "type": "string"
                                },
                                "startUrl": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "pictureAspect": {
                            "type": "string"
                        },
                        "themeColor": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "coast": {
                    "properties": {
                        "backgroundColor": {
                            "type": "string"
                        },
                        "margin": {
                            "type": [
                                "string",
                                "number"
                            ]
                        },
                        "pictureAspect": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "desktopBrowser": {
                    "properties": {},
                    "type": "object"
                },
                "firefoxApp": {
                    "properties": {
                        "backgroundColor": {
                            "type": "string"
                        },
                        "circleInnerMargin": {
                            "type": "string"
                        },
                        "keepPictureInCircle": {
                            "type": [
                                "string",
                                "boolean"
                            ]
                        },
                        "manifest": {
                            "properties": {
                                "appDescription": {
                                    "type": "string"
                                },
                                "appName": {
                                    "type": "string"
                                },
                                "developerName": {
                                    "type": "string"
                                },
                                "developerUrl": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "margin": {
                            "type": [
                                "string",
                                "number"
                            ]
                        },
                        "pictureAspect": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "ios": {
                    "properties": {
                        "assets": {
                            "properties": {
                                "declareOnlyDefaultIcon": {
                                    "type": "boolean"
                                },
                                "ios6AndPriorIcons": {
                                    "type": "boolean"
                                },
                                "ios7AndLaterIcons": {
                                    "type": "boolean"
                                },
                                "precomposedIcons": {
                                    "type": "boolean"
                                }
                            },
                            "type": "object"
                        },
                        "backgroundColor": {
                            "type": "string"
                        },
                        "margin": {
                            "type": [
                                "string",
                                "number"
                            ]
                        },
                        "pictureAspect": {
                            "type": "string"
                        },
                        "startupImage": {
                            "properties": {
                                "backgroundColor": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "openGraph": {
                    "properties": {
                        "backgroundColor": {
                            "type": "string"
                        },
                        "margin": {
                            "type": [
                                "string",
                                "number"
                            ]
                        },
                        "pictureAspect": {
                            "type": "string"
                        },
                        "ratio": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "safariPinnedTab": {
                    "properties": {
                        "pictureAspect": {
                            "type": "string"
                        },
                        "themeColor": {
                            "type": "string"
                        },
                        "threshold": {
                            "type": "number"
                        }
                    },
                    "type": "object"
                },
                "windows": {
                    "properties": {
                        "assets": {
                            "properties": {
                                "windows10Ie11EdgeTiles": {
                                    "properties": {
                                        "big": {
                                            "type": "boolean"
                                        },
                                        "medium": {
                                            "type": "boolean"
                                        },
                                        "rectangle": {
                                            "type": "boolean"
                                        },
                                        "small": {
                                            "type": "boolean"
                                        }
                                    },
                                    "type": "object"
                                },
                                "windows80Ie10Tile": {
                                    "type": "boolean"
                                }
                            },
                            "type": "object"
                        },
                        "backgroundColor": {
                            "type": "string"
                        },
                        "onConflict": {
                            "type": "string"
                        },
                        "pictureAspect": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "yandexBrowser": {
                    "properties": {
                        "backgroundColor": {
                            "type": "string"
                        },
                        "manifest": {
                            "properties": {
                                "showTitle": {
                                    "type": "boolean"
                                },
                                "version": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "apiKey": {
            "type": "string"
        },
        "appDescription": {
            "type": "string"
        },
        "appName": {
            "description": "see https://github.com/haydenbleasel/favicons#usage",
            "type": "string"
        },
        "background": {
            "description": "see https://github.com/haydenbleasel/favicons#usage",
            "type": "string"
        },
        "design": {
            "$ref": "#/definitions/IconDesign",
            "description": "see https://github.com/haydenbleasel/favicons#usage"
        },
        "developerName": {
            "type": "string"
        },
        "developerUrl": {
            "type": "string"
        },
        "dir": {
            "type": "string"
        },
        "display": {
            "description": "Android display: \"browser\" or \"standalone\".",
            "type": "string"
        },
        "emitFaviconIcoToOutDirRoot": {
            "description": "Copy 'favicon.ico' file to root output directory",
            "type": "boolean"
        },
        "emitStats": {
            "default": false,
            "description": "Emit all stats of the generated icons",
            "type": "boolean"
        },
        "iconsPath": {
            "description": "The prefix for all image files (might be a folder or a name)",
            "type": "string"
        },
        "lang": {
            "type": "string"
        },
        "masterPicture": {
            "description": "Your source logo",
            "type": "string"
        },
        "online": {
            "description": "Use RealFaviconGenerator to create favicons? `boolean`",
            "type": "boolean"
        },
        "orientation": {
            "description": "Android orientation: \"portrait\" or \"landscape\".",
            "type": "string"
        },
        "persistentCache": {
            "type": "boolean"
        },
        "preferOnline": {
            "description": "Use offline generation, if online generation has failed. `boolean`",
            "type": "boolean"
        },
        "settings": {
            "properties": {
                "compression": {
                    "type": "string"
                },
                "errorOnImageTooSmall": {
                    "type": "boolean"
                },
                "scalingAlgorithm": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "startUrl": {
            "description": "Android start application's Url.",
            "type": "string"
        },
        "statsFilename": {
            "description": "The name of the json containing all favicon information",
            "type": "string"
        },
        "version": {
            "description": "Your application's version number.",
            "type": "string"
        },
        "versioning": {
            "anyOf": [
                {
                    "properties": {
                        "paramName": {
                            "type": "string"
                        },
                        "paramValue": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                {
                    "type": "boolean"
                }
            ]
        }
    },
    "type": "object"
}

=== DagonMetric/angular-build/templates/aspnetcore/angularstarter/content/ClientApp/favicon-config.json
{
  "$schema": "../node_modules/@bizappframework/angular-build/configs/favicon-config-schema-draft-04.json#",
  "masterPicture": "favicon.svg",
  "iconsPath": "icons-[hash]/",
  "design": {
    "desktopBrowser": {},
    "androidChrome": {
      "pictureAspect": "noChange",
      "manifest": {
        "display": "standalone",
        "orientation": "notSet",
        "onConflict": "override",
        "declared": true
      },
      "assets": {
        "legacyIcon": false,
        "lowResolutionIcons": false
      }
    },
    "ios": {
      "pictureAspect": "backgroundAndMargin",
      "margin": 0,
      "assets": {
        "ios6AndPriorIcons": false,
        "ios7AndLaterIcons": true,
        "precomposedIcons": false,
        "declareOnlyDefaultIcon": true
      },
      "startupImage": {}
    },
    "safariPinnedTab": {
      "pictureAspect": "silhouette"
    },
    "windows": {
      "pictureAspect": "noChange",
      "onConflict": "override",
      "assets": {
        "windows80Ie10Tile": false,
        "windows10Ie11EdgeTiles": {
          "small": false,
          "medium": true,
          "big": false,
          "rectangle": false
        }
      }
    },
    "firefoxApp": {
      "pictureAspect": "circle",
      "keepPictureInCircle": true,
      "circleInnerMargin": "0",
      "margin": 0,
      "manifest": {}
    },
    "coast": {
      "pictureAspect": "backgroundAndMargin",
      "margin": 0
    },
    "openGraph": {
      "pictureAspect": "backgroundAndMargin",
      "margin": 0,
      "ratio": "1.91:1"
    }
  },
  "settings": {
    "scalingAlgorithm": "Mitchell",
    "errorOnImageTooSmall": true
  },
  "appName": "",
  "version": "1.0",
  "appDescription": "",
  "developerName": "",
  "developerUrl": "",
  "background": "#ffffff",
  "online": false,
  "preferOnline": true,
  "emitFaviconIcoToOutDirRoot": true
}
